spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:lupa_federal}
spring.datasource.username=${POSTGRES_USER:lupa}
spring.datasource.password=${POSTGRES_PASSWORD:lupa}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.flyway.schemas=lupa
spring.flyway.default-schema=lupa
spring.jpa.properties.hibernate.default_schema=lupa

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html